# -*- coding: utf-8 -*-
"""Decision Tree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQmTVBJ80Rd6ViVSjhYi4LSFql35PEh_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv("/content/drive/MyDrive/diabetes.csv")
print(dataset.head())

plt.figure(figsize=(8,6))
sns.heatmap(dataset.corr(),annot=True)
plt.title("correlation heatmap")
plt.show()

dataset.hist(figsize=(10,8))
plt.show()

plt.figure(figsize=(10,8))
dataset.boxplot()
plt.title("outlier detection")
plt.show()

Q1=dataset.quantile(0.25)
Q3=dataset.quantile(0.75)
IQR=Q3-Q1
dataset=dataset[~(dataset<(Q1-1.5*IQR))|(dataset>(Q3+1.5*IQR)).any(axis=1)]
print("dataset shape after removing outliers:,dataset.shape")

plt.figure(figsize=(10,6))
dataset.boxplot()
plt.title("outlier dectection")
plt.show()

x=dataset[["Glucose","BMI"]].values
y=dataset["Outcome"].values
plt.scatter(dataset["Glucose"],dataset["BMI"],c=y)
plt.xlabel("Glucose")
plt.ylabel("BMI")
plt.show

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.25,random_state=0)

from sklearn.tree import  DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',random_state=0)
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
print("Predictions:",y_pred)

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(cm)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

plt.scatter(x_train[:,0],x_train[:,1],c=y_train)
plt.xlabel("Glucose")
plt.ylabel("BMI")
plt.show()

plt.scatter(x_test[:,0],x_test[:,1],c=y_test)
plt.xlabel("Glucose")
plt.ylabel("BMI")
plt.title("Test Data")
plt.show()